application:
  name: aggregator

grpc:
  server:
    port: 0

kafka:
  bootstrap-servers: localhost:9092
  group-id: action-group
  action-topic: stats.user-actions.v1
  similarity-topic: stats.events-similarity.v1
  auto-commit: true