# Server Configuration
server:
  port: 0

# JPA / Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    show-sql: false
  sql:
    init.mode: always

  # DataSource
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/mainDB_local
    username: localuser
    password: localpass

# Logging
logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: INFO