services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                  'kafka-topics --create --topic stats.user-actions.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092 && \
                  kafka-topics --create --topic stats.events-similarity.v1 \
                               --partitions 1 --replication-factor 1 --if-not-exists \
                               --bootstrap-server kafka:29092 && \'"
    init: true

  analyzer-db:
    image: postgres:16.1
    container_name: postgres-ewm-analyzer-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=analyzer_server
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  category-db:
    image: postgres:16.1
    container_name: postgres-category-service-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=category_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  comments-db:
    image: postgres:16.1
    container_name: postgres-comments-service-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=comments_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  compilation-db:
    image: postgres:16.1
    container_name: postgres-compilation-service-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=compilation_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  event-db:
    image: postgres:16.1
    container_name: postgres-event-service-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_DB=event_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: postgres-user-service-db
    ports:
      - "6547:5432"
    environment:
      - POSTGRES_DB=user_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: postgres-request-service-db
    ports:
      - "6548:5432"
    environment:
      - POSTGRES_DB=request_service
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10