application:
  name: category-service

spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    jdbc:
      time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/category_service
    username: localuser
    password: localpass

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ru.yandex.practicum.category: DEBUG
    org.springframework.orm.jpa: WARN
    org.springframework.orm.jpa.JpaTransactionManager: WARN
    org.springframework.transaction: WARN
    org.springframework.transaction.interceptor: WARN

server:
  port: 0
