server:
  port: 0
grpc:
  server:
    port: 0

application:
  name: collector

kafka:
  bootstrap-servers: localhost:9092
  action-topic: stats.user-actions.v1
  similarity-topic: stats.events-similarity.v1
  consumer:
    auto-offset-reset: latest
