spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          refresh-interval: 60000
      routes:
        - id: public_event_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /events
            - Method=GET
        - id: public_event_by_id_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /events/{eventId:[0-9]+}
            - Method=GET
        - id: public_event_comments_by_id_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /events/{userId:[0-9]+}/comments
            - Method=GET
        - id: private_event_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/events
            - Method=GET,POST
        - id: private_event_specific_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/events/{eventId:[0-9]+}
            - Method=GET,PATCH
        - id: private_event_requests_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/events/{eventId:[0-9]+}/requests
            - Method=GET,PATCH
        - id: admin_events_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /admin/events
            - Method=GET
        - id: admin_event_by_id_route
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                pattern: /admin/events/{eventId:[0-9]+}
            - Method=PATCH
        - id: public_categories_route
          uri: lb://category-service
          predicates:
            - name: Path
              args:
                pattern: /categories
            - Method=GET
        - id: public_categories_by_id_route
          uri: lb://category-service
          predicates:
            - name: Path
              args:
                pattern: /categories/{catId:[0-9]+}
            - Method=GET
        - id: admin_categories_route
          uri: lb://category-service
          predicates:
            - name: Path
              args:
                pattern: /admin/categories
            - Method=POST
        - id: admin_categories_specific_route
          uri: lb://category-service
          predicates:
            - name: Path
              args:
                pattern: /admin/categories/{catId:[0-9]+}
            - Method=DELETE,PATCH
        - id: public_compilations_route
          uri: lb://compilation-service
          predicates:
            - name: Path
              args:
                pattern: /compilations
            - Method=GET
        - id: public_compilations_by_id_route
          uri: lb://compilation-service
          predicates:
            - name: Path
              args:
                pattern: /compilations/{compId:[0-9]+}
            - Method=GET
        - id: admin_compilations_route
          uri: lb://compilation-service
          predicates:
            - name: Path
              args:
                pattern: /admin/compilations
            - Method=POST
        - id: admin_compilations_specific_route
          uri: lb://compilation-service
          predicates:
            - name: Path
              args:
                pattern: /admin/compilations/{compId:[0-9]+}
            - Method=DELETE,PATCH
        - id: admin_users_route
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /admin/users
            - Method=GET,POST
        - id: admin_users_delete_route
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /admin/users/{userId:[0-9]+}
            - Method=DELETE
        - id: private_requests_route
          uri: lb://request-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/requests
            - Method=GET,POST
        - id: private_requests_cancel_route
          uri: lb://request-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/requests/{reqId:[0-9]+}/cancel
            - Method=PATCH
        - id: private_comments_route
          uri: lb://comments-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/comments
            - Method=POST,GET
        - id: private_comments_specific_route
          uri: lb://comments-service
          predicates:
            - name: Path
              args:
                pattern: /users/{userId:[0-9]+}/comments/{commentId:[0-9]+}
            - Method=DELETE,PATCH,GET
        - id: admin_comments_route
          uri: lb://comments-service
          predicates:
            - name: Path
              args:
                pattern: /admin/comments
            - Method=GET
        - id: admin_comments_patch_by_id_route
          uri: lb://comments-service
          predicates:
            - name: Path
              args:
                pattern: /admin/comments/{commentId:[0-9]+}
            - Method=PATCH

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG