server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    show-sql: false
  sql:
    init.mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/statDB_local
    username: localuser
    password: localpass

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: INFO