application:
  name: event-service

spring:
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    jdbc:
      time-zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6546/event_service
    username: localuser
    password: localpass
  management:
    endpoints:
      web:
        exposure:
          include: "*"

grpc:
  client:
    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 0

server:
  port: 0

logging:
  level:
    org.springframework.orm.jpa: WARN
    org.springframework.orm.jpa.JpaTransactionManager: WARN
    org.springframework.transaction: WARN
    org.springframework.transaction.interceptor: WARN